server:
  port: 9529

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mybatis/mappers/*.xml
  type-aliases-package: com.shirodemo.demo0808.entity
mapper:
  mappers: com.shirodemo.demo0808.config.mybaits.MyMapper
  not-empty: false
  identity: MYSQL


logging:
  level:
    com:
      shirodemo:
        demo0808: debug

